"""add fcm token table

Revision ID: 03efd281367b
Revises: e9bf9ffff5d8
Create Date: 2026-02-26 00:49:11.552291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03efd281367b'
down_revision = 'e9bf9ffff5d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcm_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fcm_token')
    # ### end Alembic commands ###
