"""Add FCM token to delivery person

Revision ID: 0d204eb33e7c
Revises: c551af59152a
Create Date: 2026-07-16 20:17:03.530348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d204eb33e7c'
down_revision = 'c551af59152a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_person', schema=None) as batch_op:
        batch_op.drop_column('fcm_token')

    # ### end Alembic commands ###
