"""add restaurant_delivery mapping

Revision ID: 0d903bb14856
Revises: ed536645ba53
Create Date: 2026-01-14 00:44:22.550493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d903bb14856'
down_revision = 'ed536645ba53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_distance', sa.Float(), nullable=True),
    sa.Column('base_charge', sa.Integer(), nullable=True),
    sa.Column('slab_1_upto', sa.Float(), nullable=True),
    sa.Column('slab_1_charge', sa.Integer(), nullable=True),
    sa.Column('slab_2_upto', sa.Float(), nullable=True),
    sa.Column('slab_2_charge', sa.Integer(), nullable=True),
    sa.Column('slab_3_upto', sa.Float(), nullable=True),
    sa.Column('slab_3_charge', sa.Integer(), nullable=True),
    sa.Column('max_charge', sa.Integer(), nullable=True),
    sa.Column('free_delivery_min_order', sa.Integer(), nullable=True),
    sa.Column('night_surge', sa.Integer(), nullable=True),
    sa.Column('is_night_surge_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('delivery_settings')
    # ### end Alembic commands ###
