"""add restaurant start_date and status

Revision ID: 12a6d730aef8
Revises: c53496d80339
Create Date: 2026-01-09 22:11:10.947845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12a6d730aef8'
down_revision = 'c53496d80339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('delivery_charge',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('free_delivery_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('is_accepting_orders')
        batch_op.drop_column('accept_orders_until')
        batch_op.drop_column('location')
        batch_op.drop_column('sheet_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sheet_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('accept_orders_until', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_accepting_orders', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('free_delivery_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('delivery_charge',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
