"""Added smart fields to FcmToken

Revision ID: 1cdb45bd7ebf
Revises: 03efd281367b
Create Date: 2026-02-27 15:36:23.815969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdb45bd7ebf'
down_revision = '03efd281367b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcm_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_active', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('coins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('badge', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcm_token', schema=None) as batch_op:
        batch_op.drop_column('badge')
        batch_op.drop_column('coins')
        batch_op.drop_column('last_active')
        batch_op.drop_column('restaurant_id')
        batch_op.drop_column('city')
        batch_op.drop_column('device')

    # ### end Alembic commands ###
