"""Add payment QR fields

Revision ID: 20334e18b16d
Revises: a1836a8c9027
Create Date: 2026-06-30 16:31:43.643065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20334e18b16d'
down_revision = 'a1836a8c9027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_qr_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_qr_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('payment_qr_status', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_qr_status')
        batch_op.drop_column('payment_qr_image_url')
        batch_op.drop_column('payment_qr_id')

    # ### end Alembic commands ###
