"""add assign_type to order_assignment

Revision ID: 22d1e6c8290e
Revises: 302ffbf744e3
Create Date: 2026-01-11 07:44:40.310628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d1e6c8290e'
down_revision = '302ffbf744e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assign_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_assignment', schema=None) as batch_op:
        batch_op.drop_column('assign_type')

    # ### end Alembic commands ###
