"""Add delivery assignment settings

Revision ID: 23183a3233a2
Revises: 4012f28c4eed
Create Date: 2026-07-20 17:13:13.916063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23183a3233a2'
down_revision = '4012f28c4eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_mode', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('auto_assign_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rider_search_radius', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('maximum_search_radius', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rider_accept_timeout', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('allow_manual_override', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_multiple_orders', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('max_orders_per_rider', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_settings', schema=None) as batch_op:
        batch_op.drop_column('max_orders_per_rider')
        batch_op.drop_column('allow_multiple_orders')
        batch_op.drop_column('allow_manual_override')
        batch_op.drop_column('rider_accept_timeout')
        batch_op.drop_column('maximum_search_radius')
        batch_op.drop_column('rider_search_radius')
        batch_op.drop_column('auto_assign_enabled')
        batch_op.drop_column('assignment_mode')

    # ### end Alembic commands ###
