"""Add limited drop / flash sale fields to Restaurant

Revision ID: 23b2996189e6
Revises: b937073b396c
Create Date: 2026-01-24 01:48:44.033134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b2996189e6'
down_revision = 'b937073b396c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_limited_drop', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('limited_item_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('limited_total_qty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('limited_remaining_qty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('limited_start_datetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('limited_end_datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('limited_end_datetime')
        batch_op.drop_column('limited_start_datetime')
        batch_op.drop_column('limited_remaining_qty')
        batch_op.drop_column('limited_total_qty')
        batch_op.drop_column('limited_item_name')
        batch_op.drop_column('is_limited_drop')

    # ### end Alembic commands ###
