"""update restaurant fields

Revision ID: 302ffbf744e3
Revises: eb0b8f640606
Create Date: 2026-01-10 14:37:06.677977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302ffbf744e3'
down_revision = 'eb0b8f640606'
branch_labels = None
depends_on = None

def upgrade():
    # 1️⃣ Add column WITH DEFAULT
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_accepting_orders',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true()
            )
        )
        batch_op.add_column(
            sa.Column('accept_orders_until', sa.Time(), nullable=True)
        )

    # 2️⃣ Remove default after data is safe
    op.alter_column(
        'restaurant',
        'is_accepting_orders',
        server_default=None
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('accept_orders_until')
        batch_op.drop_column('is_accepting_orders')

    # ### end Alembic commands ###
