"""add coin redemption fields to order

Revision ID: 308e76684379
Revises: 587b71057f5c
Create Date: 2026-02-07 22:01:53.953539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308e76684379'
down_revision = '587b71057f5c'
branch_labels = None
depends_on = None


def upgrade():
    # 1) Add redemption columns as nullable
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins_redeemed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('coins_discount_amount', sa.Float(), nullable=True))

    # 2) Populate defaults for OLD rows
    op.execute('UPDATE "order" SET coins_redeemed = 0 WHERE coins_redeemed IS NULL')
    op.execute('UPDATE "order" SET coins_discount_amount = 0 WHERE coins_discount_amount IS NULL')
    op.execute('UPDATE "order" SET coins_given = FALSE WHERE coins_given IS NULL')

    # 3) Enforce NOT NULL
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('coins_redeemed', nullable=False)
        batch_op.alter_column('coins_discount_amount', nullable=False)
        batch_op.alter_column(
            'coins_given',
            existing_type=sa.BOOLEAN(),
            nullable=False
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('coins_given',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('coins_discount_amount')
        batch_op.drop_column('coins_redeemed')

    # ### end Alembic commands ###
