"""add reward system tables

Revision ID: 3915507986f8
Revises: 59ee4156ff25
Create Date: 2026-02-06 17:06:35.207232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3915507986f8'
down_revision = '59ee4156ff25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earn_per_rupees', sa.Integer(), nullable=True),
    sa.Column('earn_coins', sa.Integer(), nullable=True),
    sa.Column('coin_value_rupees', sa.Float(), nullable=True),
    sa.Column('min_redeem_coins', sa.Integer(), nullable=True),
    sa.Column('max_redeem_percent', sa.Integer(), nullable=True),
    sa.Column('coins_expiry_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reward_setting')
    op.drop_table('reward_event')
    op.drop_table('coin_ledger')
    # ### end Alembic commands ###
