"""add created_at to restaurant

Revision ID: 3a2ad5c0b1cf
Revises: 6ecb0979ede1
Create Date: 2026-02-10 11:14:13.234451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2ad5c0b1cf'
down_revision = '6ecb0979ede1'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created_at',
                sa.DateTime(),
                nullable=False,
                server_default=sa.text('NOW()')
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
