"""add location columns to delivery_person

Revision ID: 3e92ffeb8a40
Revises: 74aedd3f1e05
Create Date: 2026-01-05 01:28:06.906418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e92ffeb8a40'
down_revision = '74aedd3f1e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_person', schema=None) as batch_op:
        batch_op.drop_column('is_online')

    # ### end Alembic commands ###
