"""Add push_subscription to DeliveryPerson

Revision ID: 4012f28c4eed
Revises: 0d204eb33e7c
Create Date: 2026-07-16 20:51:02.590105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4012f28c4eed'
down_revision = '0d204eb33e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_subscription', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_person', schema=None) as batch_op:
        batch_op.drop_column('push_subscription')

    # ### end Alembic commands ###
