"""add last_reward_coins to customer

Revision ID: 587b71057f5c
Revises: 0ddd2bf0d890
Create Date: 2026-02-07 16:58:22.871669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587b71057f5c'
down_revision = '0ddd2bf0d890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reward_coins', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('last_reward_coins')

    # ### end Alembic commands ###
