"""add timezone to restaurant

Revision ID: 59ee4156ff25
Revises: 23b2996189e6
Create Date: 2026-02-03 00:15:32.444043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ee4156ff25'
down_revision = '23b2996189e6'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'timezone',
                sa.String(length=50),
                nullable=False,
                server_default='Asia/Kolkata'
            )
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
