"""add order_assignment table

Revision ID: 60404e3d6489
Revises: 7d5af245e5cf
Create Date: 2026-01-08 00:02:24.203363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60404e3d6489'
down_revision = '7d5af245e5cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_person_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_person_id'], ['delivery_person.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_assignment')
    # ### end Alembic commands ###
