"""add food_item_id to order_item

Revision ID: 69221c032109
Revises: remove_platform_offer_id
Create Date: 2026-01-06 16:39:04.388642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69221c032109'
down_revision = 'remove_platform_offer_id'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_item_id', sa.Integer(), nullable=True))
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_orderitem_fooditem', 'food_item', ['food_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orderitem_fooditem', type_='foreignkey')
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('food_item_id')

    # ### end Alembic commands ###
