"""add badge system

Revision ID: 6ecb0979ede1
Revises: 308e76684379
Create Date: 2026-02-08 17:11:40.865000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ecb0979ede1'
down_revision = '308e76684379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('required_coins', sa.Integer(), nullable=False),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'reward_badge', ['badge_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('badge_id')

    op.drop_table('reward_badge')
    # ### end Alembic commands ###
