"""Created Offer table

Revision ID: 7aa8346659d6
Revises: 1cdb45bd7ebf
Create Date: 2026-02-27 15:44:31.033983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa8346659d6'
down_revision = '1cdb45bd7ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('coupon', sa.String(length=50), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer')
    # ### end Alembic commands ###
