"""Add is_accepting_orders and accept_orders_until to Restaurant

Revision ID: 7d5af245e5cf
Revises: 8643f0e9b341
Create Date: 2026-01-06 21:03:01.776541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5af245e5cf'
down_revision = '8643f0e9b341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_offer_restaurant')
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_orderitem_fooditem'), type_='foreignkey')
        batch_op.drop_column('food_item_id')

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accepting_orders', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('accept_orders_until', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('accept_orders_until')
        batch_op.drop_column('is_accepting_orders')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orderitem_fooditem'), 'food_item', ['food_item_id'], ['id'])
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('platform_offer_restaurant',
    sa.Column('platform_offer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['platform_offer_id'], ['platform_offer.id'], name=op.f('platform_offer_restaurant_platform_offer_id_fkey')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name=op.f('platform_offer_restaurant_restaurant_id_fkey')),
    sa.PrimaryKeyConstraint('platform_offer_id', 'restaurant_id', name=op.f('platform_offer_restaurant_pkey'))
    )
    # ### end Alembic commands ###
