"""Fix platform_offer many-to-many

Revision ID: 8643f0e9b341
Revises: 69221c032109
Create Date: 2026-01-06 17:28:28.897473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8643f0e9b341'
down_revision = '69221c032109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_offer_restaurant',
    sa.Column('platform_offer_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['platform_offer_id'], ['platform_offer.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('platform_offer_id', 'restaurant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_offer_restaurant')
    # ### end Alembic commands ###
