"""add payment link fields to orders

Revision ID: 994f99d9c1bb
Revises: ce56e6d6cc40
Create Date: 2026-06-28 22:41:18.692535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994f99d9c1bb'
down_revision = 'ce56e6d6cc40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_link_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_link_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_link_url')
        batch_op.drop_column('payment_link_id')

    # ### end Alembic commands ###
