"""Add force_delivery_charge to Restaurant

Revision ID: 9de6de0b17ff
Revises: 0d903bb14856
Create Date: 2026-01-15 11:43:38.656488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de6de0b17ff'
down_revision = '0d903bb14856'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('restaurant') as batch_op:
        batch_op.add_column(
            sa.Column(
                'force_delivery_charge',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false()  # <-- this sets default for existing rows
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('force_delivery_charge')

    # ### end Alembic commands ###
