"""add platform_offer table

Revision ID: 9e65ec759ff3
Revises: 3e92ffeb8a40
Create Date: 2026-01-05 18:40:28.535524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e65ec759ff3'
down_revision = '3e92ffeb8a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('offer_type', sa.String(length=20), nullable=True),
    sa.Column('offer_value', sa.Float(), nullable=True),
    sa.Column('min_order_amount', sa.Float(), nullable=True),
    sa.Column('max_discount', sa.Float(), nullable=True),
    sa.Column('free_delivery', sa.Boolean(), nullable=True),
    sa.Column('is_first_order', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_offer')
    # ### end Alembic commands ###
