"""Add payment_qr_url to Order

Revision ID: a1836a8c9027
Revises: 994f99d9c1bb
Create Date: 2026-06-30 14:19:21.619399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1836a8c9027'
down_revision = '994f99d9c1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_qr_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_qr_url')

    # ### end Alembic commands ###
