"""Remove current_order_id from delivery_person

Revision ID: a9e65c6d8a75
Revises: df253ebcce3d
Create Date: 2026-07-20 17:47:56.296148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e65c6d8a75'
down_revision = 'df253ebcce3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_person', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('delivery_person_current_order_id_fkey'), type_='foreignkey')
        batch_op.drop_column('current_order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('delivery_person_current_order_id_fkey'), 'order', ['current_order_id'], ['id'])

    # ### end Alembic commands ###
