"""extend menu item for bakery cakes

Revision ID: b937073b396c
Revises: 478fe7a62193
Create Date: 2026-01-18 10:21:28.202711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b937073b396c'
down_revision = '478fe7a62193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('weight_prices', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('flavour', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('order_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('order_type')
        batch_op.drop_column('flavour')
        batch_op.drop_column('type')
        batch_op.drop_column('availability')
        batch_op.drop_column('image_url')
        batch_op.drop_column('weight_prices')
        batch_op.drop_column('description')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
