"""increase device_fingerprint length

Revision ID: c53496d80339
Revises: d2194107c154
Create Date: 2026-01-08 12:38:17.572713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c53496d80339'
down_revision = 'd2194107c154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon_usage', schema=None) as batch_op:
        batch_op.alter_column('device_fingerprint',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('device_fingerprint',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('delivery_response_time')
        batch_op.drop_column('delivery_accept_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_accept_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('delivery_response_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('device_fingerprint',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('coupon_usage', schema=None) as batch_op:
        batch_op.alter_column('device_fingerprint',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
