"""Add rider assignment tracking

Revision ID: c748bb1eeb83
Revises: a9e65c6d8a75
Create Date: 2026-07-23 16:30:37.129971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c748bb1eeb83'
down_revision = 'a9e65c6d8a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assignment_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rider_response', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('rider_response')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('accepted_at')
        batch_op.drop_column('assignment_expires_at')
        batch_op.drop_column('assigned_at')

    # ### end Alembic commands ###
