"""Add weight category and future fields to OrderItem

Revision ID: cc1d79f1a1aa
Revises: 3e833ba8c9bf
Create Date: 2026-06-23 15:39:38.312411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1d79f1a1aa'
down_revision = '3e833ba8c9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mrp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('item_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('item_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('food_item_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('food_item_id')
        batch_op.drop_column('item_type')
        batch_op.drop_column('item_image')
        batch_op.drop_column('unit')
        batch_op.drop_column('discount')
        batch_op.drop_column('mrp')
        batch_op.drop_column('category')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
