"""Added payment fields

Revision ID: ce56e6d6cc40
Revises: cc1d79f1a1aa
Create Date: 2026-06-28 00:52:38.660332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce56e6d6cc40'
down_revision = 'cc1d79f1a1aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_source', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('payment_method_used', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_order_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_signature', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('payment_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('refund_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('refund_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('refund_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('refund_reason', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('transaction_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_verified')
        batch_op.drop_column('transaction_reference')
        batch_op.drop_column('refund_reason')
        batch_op.drop_column('refund_time')
        batch_op.drop_column('refund_amount')
        batch_op.drop_column('refund_status')
        batch_op.drop_column('payment_time')
        batch_op.drop_column('payment_signature')
        batch_op.drop_column('payment_order_id')
        batch_op.drop_column('payment_id')
        batch_op.drop_column('payment_method_used')
        batch_op.drop_column('payment_source')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
