"""add order_assignment table

Revision ID: d2194107c154
Revises: 60404e3d6489
Create Date: 2026-01-08 00:09:02.232337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2194107c154'
down_revision = '60404e3d6489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_accept_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivery_response_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('delivery_response_time')
        batch_op.drop_column('delivery_accept_status')

    # ### end Alembic commands ###
