"""sync restaurant location column

Revision ID: d78efe4f6b26
Revises: d61024ad0e8e
Create Date: 2026-01-09 22:55:51.266908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd78efe4f6b26'
down_revision = 'd61024ad0e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accepting_orders', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('accept_orders_until', sa.Time(), nullable=True))
        batch_op.drop_column('start_date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('accept_orders_until')
        batch_op.drop_column('is_accepting_orders')

    # ### end Alembic commands ###
