"""add coins_given flag

Revision ID: da40564f47ba
Revises: 3915507986f8
Create Date: 2026-02-06 17:22:08.220756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da40564f47ba'
down_revision = '3915507986f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin_ledger', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins_given', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('coins')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('coins_given')

    with op.batch_alter_table('coin_ledger', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
