"""Delivery availability fields

Revision ID: df253ebcce3d
Revises: 23183a3233a2
Create Date: 2026-07-20 17:17:09.453757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df253ebcce3d'
down_revision = '23183a3233a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('current_order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_assignment', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'order', ['current_order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_assignment')
        batch_op.drop_column('current_order_id')
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###
