"""Add tags to restaurant

Revision ID: e9bf9ffff5d8
Revises: 8a67f63c539b
Create Date: 2026-02-14 14:22:13.958638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9bf9ffff5d8'
down_revision = '8a67f63c539b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_best_seller', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_fast_delivery', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('is_fast_delivery')
        batch_op.drop_column('is_best_seller')

    # ### end Alembic commands ###
