"""add restaurant status and start_date

Revision ID: eb0b8f640606
Revises: d78efe4f6b26
Create Date: 2026-01-09 23:06:24.759629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb0b8f640606'
down_revision = 'd78efe4f6b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_column('accept_orders_until')
        batch_op.drop_column('is_accepting_orders')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accepting_orders', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('accept_orders_until', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
