"""Add force_delivery_charge to restaurant

Revision ID: ecf703c5ce7a
Revises: 9de6de0b17ff
Create Date: 2026-01-15 16:32:24.948585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf703c5ce7a'
down_revision = '9de6de0b17ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('shop_name', sa.String(length=50), nullable=False),
    sa.Column('is_combo', sa.Boolean(), nullable=True),
    sa.Column('combo_items', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=50), nullable=True),
    sa.Column('min_delivery_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_settings')
    op.drop_table('item')
    # ### end Alembic commands ###
