"""add restaurant_delivery mapping

Revision ID: ed536645ba53
Revises: 8a17e71d0d4a
Create Date: 2026-01-14 00:14:29.018050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed536645ba53'
down_revision = '8a17e71d0d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('delivery_person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_person_id'], ['delivery_person.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'delivery_person_id', name='unique_restaurant_delivery')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_delivery')
    # ### end Alembic commands ###
